name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  update-and-restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update the bot
        env:
          RESTART_TOKEN: ${{ secrets.RESTART_TOKEN }}
        run: |
          curl -X POST "https://nexara.rababio.fr/deploy-bot?token=$RESTART_TOKEN"
